import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {Text,View,PanResponder,Platform} from 'react-native';
import {useLocalSearchParams,Link} from 'expo-router';
import {request,type Summary,type Finding} from '../../lib/api';
import {Action,Input,Page,styles} from '../../components/UI';
export default function AuditPage(){
 const {id}=useLocalSearchParams<{id:string}>(),[summary,setSummary]=useState<Summary|null>(null),[score,setScore]=useState<number|null>(null),[reason,setReason]=useState(''),[flags,setFlags]=useState<Finding[]>([]),[index,setIndex]=useState(0),[note,setNote]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reviewer,setReviewer]=useState(false),[notify,setNotify]=useState(false);
 const previousStatus=useRef<string|null>(null),notifying=useRef(false);
 useEffect(()=>{request<{role:string;is_superuser:boolean}>('/users/me').then(u=>setReviewer(u.is_superuser||['reviewer','admin'].includes(u.role))).catch(()=>setReviewer(false));},[]);
 const pan=useMemo(()=>PanResponder.create({onMoveShouldSetPanResponder:(_,g)=>!busy&&!note.trim()&&Math.abs(g.dx)>35&&Math.abs(g.dx)>Math.abs(g.dy)*2,onPanResponderRelease:(_,g)=>{if(Math.abs(g.dx)>70)setIndex(i=>Math.max(0,Math.min(flags.length-1,i+(g.dx<0?1:-1))));}}),[busy,note,flags.length]);
 const load=useCallback(async()=>{const s=await request<Summary>(`/audits/${id}`);setSummary(s);setScore(null);if(notifying.current&&previousStatus.current&&previousStatus.current!=='completed'&&s.audit.status==='completed'){import('expo-notifications').then(n=>n.scheduleNotificationAsync({content:{title:'Audit finished',body:'Open Tathya to read the current evidence and findings.'},trigger:null})).catch(()=>{});}previousStatus.current=s.audit.status;if(s.audit.status==='completed'){const b=await request<{reviewed_score:number;score_status:string;score_limit_reason?:string;coverage:{documents_changed?:boolean;resolutions_changed?:boolean}}>(`/audits/${id}/score-breakdown`);setScore(b.score_status==='insufficient_verification'||b.coverage.documents_changed||b.coverage.resolutions_changed?null:b.reviewed_score);setReason(b.score_limit_reason||'Read source evidence alongside this rating.');setFlags((await request<{data:Finding[]}>(`/audits/${id}/flags`)).data);}},[id]);
 useEffect(()=>{let alive=true;const refresh=()=>{if(alive)load().catch(e=>{if(alive){setScore(null);setError(e.message);}});};refresh();const t=setInterval(refresh,10000);return()=>{alive=false;clearInterval(t);};},[load]);
 const action=async(job:()=>Promise<void>)=>{setBusy(true);setError('');try{await job();await load();}catch(e){setError(e instanceof Error?e.message:'The request failed.');}finally{setBusy(false);}};
 const flag=flags[Math.min(index,Math.max(0,flags.length-1))];
 return <Page><Text style={styles.title}>{summary?.audit.title||'Loading audit…'}</Text><Text style={styles.text}>{summary?.audit.status}</Text><Text style={styles.score}>{score==null?'Not assessed':`${score}/100`}</Text><Text style={styles.text}>{reason||summary?.audit.error_message||'Verification incomplete or refreshing.'}</Text><Action title="Refresh" disabled={busy} onPress={()=>action(async()=>{})}/>{!!summary?.verify_token&&<Link href={{pathname:"/verify",params:{token:summary.verify_token}}} style={styles.text}>Verify passport: {summary.verify_token}</Link>}{flag&&<View style={styles.card} {...pan.panHandlers}><Text style={styles.text}>{index+1} of {flags.length} · {flag.severity} · {flag.status}</Text><Text style={styles.title}>{flag.type.replace(/_/g,' ')}</Text><Text style={styles.text}>{flag.explanation}</Text>{flag.evidence?.map((e,i)=><Text key={i} style={styles.text}>{e.quote}</Text>)}<Action title="Previous finding" disabled={!index||busy||!!note.trim()} onPress={()=>{setIndex(index-1);setNote('');}}/><Action title="Next finding" disabled={index>=flags.length-1||busy||!!note.trim()} onPress={()=>{setIndex(index+1);setNote('');}}/><Text style={styles.text}>Swipe horizontally or use Previous / Next. Clear or save your note before switching findings.</Text>{reviewer&&<><Input label="Review reason" value={note} onChangeText={setNote} multiline/><Text style={styles.text}>Reviewer access required. Save a decision, then recalculate explicitly.</Text>{(['accept','dismiss','fix'] as const).map(choice=><Action key={choice} title={choice==='fix'?'Mark fixed':choice==='dismiss'?'Dismiss finding':'Accept finding'} disabled={busy||note.trim().length<3||summary?.audit.status!=='completed'} onPress={()=>action(async()=>{await request(`/audits/${id}/flags/${flag.id}/decision`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:choice,reason:note.trim(),remediation:choice==='fix'?note.trim():''})});setNote('');})}/>)}<Action title="Recalculate after review" disabled={busy} onPress={()=>action(async()=>{await request(`/audits/${id}/rescore`,{method:'POST'});})}/></>}</View>}{Platform.OS!=='web'&&<Action title={notify?'Completion alerts enabled while this screen is open':'Enable completion alert for this screen'} disabled={notify} onPress={async()=>{try{const Notifications=await import('expo-notifications');if(Platform.OS==='android')await Notifications.setNotificationChannelAsync('default',{name:'Audit completion',importance:Notifications.AndroidImportance.DEFAULT});const p=await Notifications.requestPermissionsAsync();if(p.granted){notifying.current=true;setNotify(true);}else setError('Notification permission declined. You can still refresh this audit.');}catch(e){setError(e instanceof Error?e.message:'Notifications unavailable.');}}}/>}{!!error&&<Text accessibilityRole="alert" style={styles.error}>{error}</Text>}</Page>;
}
