import {useEffect,useState} from 'react';
import {Text,View} from 'react-native';
import {Link,router} from 'expo-router';
import * as DocumentPicker from 'expo-document-picker';
import {login,logout,request,restore,setServer} from '../lib/api';
import {uploadAssets} from '../lib/upload';
import {Action,Input,Page,styles} from '../components/UI';
export default function Home(){
 const [server,setBase]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[signedIn,setSignedIn]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[audits,setAudits]=useState<{id:string;title:string;status:string}[]>([]),[selected,setSelected]=useState<DocumentPicker.DocumentPickerAsset[]>([]);
 const run=async(job:()=>Promise<void>)=>{setBusy(true);setError('');try{await job();}catch(e){setError(e instanceof Error?e.message:'The action could not finish.');}finally{setBusy(false);}};
 useEffect(()=>{restore().then(s=>{setBase(s.base);setSignedIn(s.signedIn);}).catch(e=>setError(e.message));},[]);
 const load=async()=>setAudits((await request<{data:typeof audits}>('/audits')).data);
 return <Page><Text style={styles.title}>Every fact, checked.</Text><Text style={styles.text}>Upload or scan documents, review findings and verify signed passports.</Text><Input label="Server address" value={server} onChangeText={setBase} autoCapitalize="none" keyboardType="url"/><Action title="Save server" disabled={busy} onPress={()=>run(async()=>{await setServer(server);const s=await restore();setSignedIn(s.signedIn);setAudits([]);})}/><Link href="/verify" style={styles.text}>Verify a passport without signing in</Link>{!signedIn?<View style={styles.card}><Input label="Email" value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address"/><Input label="Password" value={password} onChangeText={setPassword} secureTextEntry/><Action title={busy?'Signing in…':'Sign in'} disabled={busy||!email||!password} onPress={()=>run(async()=>{await setServer(server);await login(email,password);setPassword('');setSignedIn(true);await load();})}/></View>:<><Action title="Choose documents" disabled={busy} onPress={()=>run(async()=>{const picked=await DocumentPicker.getDocumentAsync({multiple:true,copyToCacheDirectory:true});if(!picked.canceled){setSelected(picked.assets);}})}/>{selected.length>0&&<View style={styles.card}><Text style={styles.text}>Check the order before upload. The first file is the AI document; the rest are sources.</Text>{selected.map((a,i)=><View key={`${a.uri}-${i}`}><Text style={styles.text}>{i===0?'AI document':'Source'}: {a.name}</Text>{i>0&&<Action title={`Use ${a.name} as AI document`} disabled={busy} onPress={()=>setSelected([a,...selected.filter((_,j)=>j!==i)])}/>}</View>)}<Action title="Confirm files and start audit" disabled={busy} onPress={()=>run(async()=>{const a=await uploadAssets(selected);setSelected([]);router.push(`/audit/${a.id}`);})}/><Action title="Clear selection" disabled={busy} onPress={()=>setSelected([])}/></View>}<Link href="/capture" style={styles.text}>Scan a document image</Link><Text style={styles.text}>Select the AI document first, then its reference sources. Processing runs on your server.</Text><Action title="Refresh my audits" disabled={busy} onPress={()=>run(load)}/>{audits.map(a=><Link key={a.id} href={`/audit/${a.id}`} style={styles.text}>{a.title} · {a.status}</Link>)}<Action title="Sign out" disabled={busy} onPress={()=>run(async()=>{await logout();setSignedIn(false);setAudits([]);setSelected([]);})}/></>}{!!error&&<Text accessibilityRole="alert" style={styles.error}>{error}</Text>}</Page>;
}
