import { useEffect, useRef, useState } from "react"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { livingTrustApi } from "@/api/livingTrust"
import { isReviewer, isRunning } from "@/api/audits"
import useAuth from "@/hooks/useAuth"
import { useUnsavedChanges } from "@/hooks/useUnsavedChanges"
import { QueryState, StatusPill, useAudit } from "./shared"
import { Link } from "@tanstack/react-router"

export function SourceUpdates({auditId}:{auditId:string}) {
 const {user}=useAuth(),client=useQueryClient(),{summary}=useAudit(auditId)
 const [files,setFiles]=useState<File[]>([]),[editing,setEditing]=useState(false),[enabled,setEnabled]=useState(false),[auto,setAuto]=useState(false),[note,setNote]=useState(""),[notice,setNotice]=useState("")
 const controller=useRef<AbortController|null>(null),input=useRef<HTMLInputElement|null>(null)
 const watch=useQuery({queryKey:["source-watch",auditId],queryFn:()=>livingTrustApi.watch(auditId),refetchInterval:q=>q.state.data?.enabled?15000:false})
 const refresh=async()=>{await summary.refetch();await Promise.all(["source-watch","audit-documents","source-facts","audit-score","audit-flags","policy-results","claim-graph"].map(key=>client.invalidateQueries({queryKey:[key,auditId]})))}
 const configure=useMutation({mutationFn:()=>livingTrustApi.configure(auditId,enabled,auto,note),onSuccess:async()=>{setEditing(false);setNote("");setNotice("Source watch settings saved.");await refresh()}})
 const check=useMutation({mutationFn:()=>livingTrustApi.check(auditId),onSuccess:async data=>{setNotice(data.busy?"An audit or another inbox check is running. Try again when it finishes.":`${data.imported.length} source versions imported.${data.reaudit_queued?" Re-audit queued.":" Open the audit and re-audit to apply any changes."}`);await refresh()}})
 const upload=useMutation({mutationFn:async()=>{if(!files.length)throw new Error("Choose source files first.");if(files.length>20||files.some(f=>!f.size||f.size>50*1024*1024)||files.reduce((n,f)=>n+f.size,0)>100*1024*1024)throw new Error("Choose up to 20 non-empty files: at most 50 MB each and 100 MB total.");controller.current=new AbortController();await livingTrustApi.upload(auditId,files,controller.current.signal)},onSuccess:async()=>{setFiles([]);if(input.current)input.current.value="";setNotice("Source documents uploaded. The audit will check the new versions.");await refresh()},onSettled:()=>{controller.current=null}})
 useEffect(()=>()=>controller.current?.abort(),[])
 const fingerprint=JSON.stringify(watch.data?.files.map(f=>[f.filename,f.raw_sha256,f.state]))
 useEffect(()=>{if(!watch.data)return;["audit","audit-documents","source-facts","audit-score","audit-flags","policy-results","claim-graph"].forEach(key=>client.invalidateQueries({queryKey:[key,auditId]}))},[fingerprint,auditId,client])
 useUnsavedChanges(files.length>0||(editing&&!!note.trim()))
 const busy=upload.isPending||configure.isPending||check.isPending||isRunning(summary.data?.audit.status||"")
 return <section className="product-panel"><h2>Living Trust — source updates</h2><p>Add source amendments to this document set. Reusing a source filename creates a new version; the AI document is protected from replacement here.</p>{notice&&<p role="status">{notice}</p>}
 <form onSubmit={e=>{e.preventDefault();upload.mutate()}}><label>Source documents<input ref={input} type="file" multiple disabled={busy} onChange={e=>{setFiles(Array.from(e.target.files||[]));upload.reset()}}/></label>{files.length>0&&<p>{files.map(f=>f.name).join(", ")}</p>}<button type="submit" className="primary-link" disabled={busy||!files.length}>{upload.isPending?"Uploading…":"Upload sources and re-audit"}</button>{upload.isPending&&<button type="button" className="secondary-button" onClick={()=>controller.current?.abort()}>Cancel upload</button>}</form>{upload.error&&<div role="alert"><p>{upload.error.message}</p><p>If a request timed out or was cancelled, check the audit before uploading again.</p><button type="button" className="secondary-button" onClick={()=>upload.reset()}>Clear upload error</button></div>}
 <Link className="back-link" to="/submit/$auditId" params={{auditId}}>Open audit results</Link>
 <h3>Watched source inbox</h3><QueryState loading={watch.isPending} error={watch.error} retry={()=>watch.refetch()}/>{watch.data&&<><StatusPill status={watch.data.enabled?"Watching":"Disabled"}/><p>When enabled, inbox checks are scheduled roughly every 30 seconds; importing larger files can take longer. Put source files directly in this folder; subfolders are excluded.</p><pre className="document-preview">{watch.data.inbox_path}</pre><p>Automatic re-audit: {watch.data.auto_reaudit?"enabled":"off — re-audit manually after import"}. Keep no more than 100 files in the inbox; each scan reads at most 100 MB and imports up to five changed files.</p>{watch.data.has_more_files&&<p role="alert">This inbox exceeds the 100-file scan limit. Move completed or unrelated files out so every source can be checked.</p>}{watch.data.files.map(f=><article key={f.filename} className="source-fact-record"><h4>{f.filename}</h4><StatusPill status={f.state}/>{f.error&&<p role="alert">{f.error}</p>}</article>)}</>}
 {user&&isReviewer(user)&&<><button type="button" className="secondary-button" disabled={busy} onClick={()=>{if(editing&&note.trim()&&!window.confirm("Discard your unsaved watch configuration?"))return;setEnabled(watch.data?.enabled||false);setAuto(watch.data?.auto_reaudit||false);setNote("");setEditing(true);configure.reset()}}>Configure source watch</button><button type="button" className="secondary-button" disabled={busy||!watch.data?.enabled} onClick={()=>check.mutate()}>{check.isPending?"Checking inbox…":"Check inbox now"}</button></>}
 {editing&&<form className="source-context-form" onSubmit={e=>{e.preventDefault();configure.mutate()}}><fieldset disabled={busy}><legend>Source inbox settings</legend><label><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>Watch this audit’s source inbox</label><label><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/>Re-audit automatically after importing changes</label><label>Reason for this configuration<textarea required minLength={3} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></label><button type="submit" className="primary-link" disabled={note.trim().length<3}>Save watch settings</button><button type="button" className="secondary-button" onClick={()=>{if(!note.trim()||window.confirm("Discard your unsaved watch configuration?"))setEditing(false)}}>Cancel</button></fieldset></form>}
 {(configure.error||check.error)&&<div role="alert"><p>{(configure.error||check.error)?.message}</p><button type="button" className="secondary-button" onClick={()=>{configure.reset();check.reset();watch.refetch()}}>Clear error and refresh inbox</button></div>}{check.data?.errors.map(e=><p role="alert" key={e.filename}>{e.filename}: {e.error}</p>)}</section>
}
