import {useState} from 'react'
import {useMutation,useQuery} from '@tanstack/react-query'
import {Link} from '@tanstack/react-router'
import {apiFetch} from '@/api/transport'
import {QueryState} from '../Audits/shared'
import {useUnsavedChanges} from '@/hooks/useUnsavedChanges'
import {z} from 'zod'
type Result={trial_id:string;candidate_audit_id:string;status:string;claims:{text:string;status:string;actual:string;correct:boolean}[]}
type Report={results:Result[];metrics:Record<string,number|null>}
const reportSchema=z.object({results:z.array(z.object({trial_id:z.string().uuid(),candidate_audit_id:z.string().uuid(),status:z.string(),claims:z.array(z.object({text:z.string(),status:z.string(),actual:z.string(),correct:z.boolean()})).max(50)})).max(100),metrics:z.record(z.string(),z.number().finite().nullable())})
export function TrialRunner({auditId,candidateText}:{auditId:string;candidateText:string}){
 const [text,setText]=useState(''),[status,setStatus]=useState('contradicted'),[note,setNote]=useState('')
 useUnsavedChanges(!!text.trim()||!!note.trim())
 const report=useQuery({queryKey:['document-trials',auditId],enabled:!!auditId,queryFn:async():Promise<Report>=>{const r=await apiFetch(`/challenges/${auditId}/trials`);return reportSchema.parse(await r.json())},refetchInterval:q=>q.state.data?.results.some(r=>['queued','processing'].includes(r.status))?5000:false})
 const run=useMutation({mutationFn:async()=>{const r=await apiFetch(`/challenges/${auditId}/trials`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({candidate_text:candidateText,expected:[{text,status,category:'other'}],note})});return r.json()},onSuccess:async()=>{await report.refetch()}})
 if(!auditId)return null
 return <section className="product-panel"><h2>Run a candidate through the audit pipeline</h2><p>A separate audit uses copies of the current source text. Original documents stay intact. Your expected label is stored on the parent audit and is not passed to the verifier. Global enabled policies apply; parent reviewer decisions and audit-specific policies are not copied.</p><form className="source-context-form" onSubmit={e=>{e.preventDefault();run.mutate()}}><fieldset disabled={run.isPending}><label>Exact candidate claim<textarea required value={text} onChange={e=>setText(e.target.value)} maxLength={2000}/></label><label>Reviewer expected result<select value={status} onChange={e=>setStatus(e.target.value)}><option value="contradicted">Contradicted</option><option value="unsupported">Unsupported</option><option value="supported">Supported — clean control</option></select></label><label>Reason for this expected result<textarea required minLength={3} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></label><button type="submit" className="primary-link" disabled={!candidateText.includes(text)||text.trim().length<3||note.trim().length<3||run.isPending}>{run.isPending?'Starting trial…':'Run isolated candidate'}</button></fieldset></form><QueryState loading={report.isPending} error={report.error||run.error} retry={()=>report.refetch()}/>{report.data&&<><p>Measured labelled claims: {report.data.metrics.labelled_claims}. Precision: {report.data.metrics.precision===null?'Not measured':report.data.metrics.precision}. Recall: {report.data.metrics.recall===null?'Not measured':report.data.metrics.recall}. These are reviewer-declared test labels, not independent production calibration.</p>{report.data.results.map(r=><article key={r.trial_id} className="source-fact-record"><h3>Trial {r.trial_id.slice(0,8)} · {r.status}</h3><Link to="/submit/$auditId" params={{auditId:r.candidate_audit_id}}>Open candidate audit</Link>{r.claims.map(c=><p key={c.text}>{c.text} — expected {c.status}; recorded {c.actual}. {c.correct?'Matched':'Did not match'}</p>)}</article>)}</>}</section>
}
