const {chromium,expect}=require('@playwright/test');
const path=require('node:path');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chromium'});
 const page=await browser.newPage({viewport:{width:1600,height:1000}});
 await page.emulateMedia({reducedMotion:'reduce'});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const base=process.env.PREVIEW_URL||'http://127.0.0.1:4183';
 const checks=[]; page.setDefaultTimeout(60000); page.setDefaultNavigationTimeout(120000);
 await page.goto(base+'/control/workspace/AUD-1042',{waitUntil:'domcontentloaded'});
 await expect(page.locator('.finding-card').first()).toBeVisible();
 await page.waitForTimeout(2600);
 await page.screenshot({path:'docs/phase3-polish/screenshots/workspace-desktop.png',fullPage:true});
 const flags=page.locator('.finding-card');
 await flags.nth(1).click();
 await expect(flags.nth(1)).toHaveAttribute('aria-pressed','true');
 await expect(page.locator('.heatmap-gutter [aria-pressed="true"]')).toHaveAttribute('aria-label',/Section 2/);
 await expect(page.locator('.evidence-detail')).toContainText('22 Dec');
 checks.push('finding → document / heatmap / evidence');
 await page.locator('.heatmap-gutter [role="button"]').nth(3).focus();
 await page.keyboard.press('Enter');
 await expect(flags.nth(3)).toHaveAttribute('aria-pressed','true');
 checks.push('keyboard heatmap → finding / evidence');
 await page.getByRole('button',{name:'Toggle document heatmap',exact:true}).click();
 await expect(page.locator('.heatmap-gutter')).toHaveCount(0);
 await page.getByRole('button',{name:'Toggle document heatmap',exact:true}).click();
 await expect(page.locator('.heatmap-gutter')).toBeVisible();
 checks.push('heatmap toggle');
 await page.getByRole('button',{name:'HIGH (2)',exact:true}).click();
 await expect(flags).toHaveCount(2);
 await page.getByRole('button',{name:'All Findings',exact:true}).click();
 await expect(flags).toHaveCount(4);
 checks.push('severity filters / clear');
 await page.getByRole('button',{name:'Trust Waterfall',exact:true}).click();
 await expect(page.getByText('Deterministic point deductions computed directly', {exact:false})).toBeVisible();
 await page.getByRole('button',{name:'Evidence Graph',exact:true}).click();
 await expect(page.locator('.react-flow')).toBeVisible();
 await page.getByRole('button',{name:'Ground Truth Evidence',exact:true}).click();
 checks.push('existing waterfall / graph tabs');
 await page.setViewportSize({width:390,height:844});
 await page.getByRole('button',{name:'Findings (4)',exact:true}).click();
 await expect(flags.first()).toBeVisible();
 await page.waitForTimeout(300); await page.evaluate(()=>{document.querySelectorAll('*').forEach(el=>{if(el.scrollTop)el.scrollTo({top:0,behavior:'instant'});});window.scrollTo(0,0);});
 await page.screenshot({path:'docs/phase3-polish/screenshots/workspace-mobile-findings.png',fullPage:true});
 await flags.first().screenshot({path:'docs/phase3-polish/screenshots/workspace-mobile-finding-detail.png'});
 await flags.first().click();
 await expect(page.locator('.evidence-detail')).toBeVisible();
 await page.waitForTimeout(300); await page.evaluate(()=>{document.querySelectorAll('*').forEach(el=>{if(el.scrollTop)el.scrollTo({top:0,behavior:'instant'});});window.scrollTo(0,0);});
 await page.screenshot({path:'docs/phase3-polish/screenshots/workspace-mobile-evidence.png',fullPage:true});
 await page.getByRole('button',{name:'Document & Heatmap',exact:true}).click();
 await expect(page.locator('.document-reader')).toBeVisible();
 await page.waitForTimeout(300); await page.evaluate(()=>{document.querySelectorAll('*').forEach(el=>{if(el.scrollTop)el.scrollTo({top:0,behavior:'instant'});});window.scrollTo(0,0);});
 await page.screenshot({path:'docs/phase3-polish/screenshots/workspace-mobile-document.png',fullPage:true});
 if(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth))throw Error('Mobile horizontal overflow');
 checks.push('390px layout / panel switching / no page overflow');
 await page.setViewportSize({width:820,height:1180});
 await page.screenshot({path:'docs/phase3-polish/screenshots/workspace-tablet.png',fullPage:true});
 checks.push('tablet layout');
 await page.setViewportSize({width:1600,height:1000});
 await page.getByRole('button',{name:'Accept Finding',exact:true}).click();
 await expect(flags.first()).toContainText('Confirmed Risk');
 checks.push('existing reviewer accept action');
 await flags.nth(1).click();
 await page.getByRole('button',{name:'Dismiss...',exact:true}).click();
 await expect(page.getByRole('button',{name:'Confirm Dismissal',exact:true})).toBeDisabled();
 await page.locator('textarea').fill('Review regression check: source verified.');
 await page.getByRole('button',{name:'Confirm Dismissal',exact:true}).click();
 await expect(flags.nth(1)).toContainText('Dismissed');
 await flags.nth(2).click();
 await page.getByRole('button',{name:'Apply Fix',exact:true}).click();
 await expect(flags.nth(2)).toContainText('Remediated');
 checks.push('existing dismiss note validation / fix action');
 for(const url of ['/login','/submit','/control/queue','/verify/PASSPORT-88219-AUD1042-CRIT']){
  await page.goto(base+url);await page.waitForTimeout(2800);await expect(page.locator('body')).not.toBeEmpty();
 }
 checks.push('login / submit / queue / verifier routes');
 await page.goto(base+'/control/workspace/does-not-exist');
 await expect(page.getByText('Audit Not Found',{exact:true})).toBeVisible();
 checks.push('audit not found');
 if(errors.length)throw Error(errors.join('\n'));
 console.log(JSON.stringify({passed:true,checks,uncaughtErrors:errors},null,2));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
