import { StyleSheet } from "react-native"
export const colors = {
  background: "#111b18",
  card: "#1b2722",
  line: "#34433a",
  text: "#edf0e8",
  muted: "#a6b7ab",
  accent: "#bdd7bb",
  amber: "#d7b57c",
}
export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  scroll: { padding: 24, paddingBottom: 120 },
  eyebrow: {
    fontSize: 10,
    letterSpacing: 2,
    color: colors.amber,
    fontWeight: "600",
  },
  title: {
    fontSize: 32,
    letterSpacing: -1,
    color: colors.text,
    fontWeight: "600",
    marginTop: 14,
  },
  description: {
    fontSize: 14,
    lineHeight: 23,
    color: colors.muted,
    marginTop: 12,
  },
  card: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 16,
    padding: 22,
    marginTop: 24,
  },
  cardTitle: { fontSize: 15, fontWeight: "600", color: colors.text },
  button: {
    backgroundColor: colors.accent,
    borderRadius: 12,
    padding: 15,
    alignItems: "center",
    minHeight: 48,
    justifyContent: "center",
  },
  buttonText: { color: colors.background, fontSize: 13, fontWeight: "600" },
  outlineButton: {
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 12,
    padding: 15,
    alignItems: "center",
    minHeight: 48,
  },
  outlineText: { color: colors.text, fontSize: 13, fontWeight: "500" },
  input: {
    color: colors.text,
    backgroundColor: colors.background,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 9,
    padding: 13,
    marginVertical: 15,
    fontSize: 13,
  },
  small: { fontSize: 11, color: colors.muted, lineHeight: 18, marginTop: 12 },
  error: { fontSize: 12, lineHeight: 20, color: "#eda899", marginTop: 14 },
  sectionLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: colors.muted,
    letterSpacing: 1,
    marginTop: 30,
  },
  rule: { height: 1, backgroundColor: colors.line, marginVertical: 20 },
})
