// Run from the repository root against the frontend production preview on port 4173.
require('node:fs').mkdirSync('artifacts/ui-review',{recursive:true});
const {chromium,expect:baseExpect}=require('@playwright/test');const expect=baseExpect.configure({timeout:30000});
const id='11111111-1111-4111-8111-111111111111';
const records=[{id,title:'Preview · Cloud procurement agreement',status:'completed',created_at:'2026-10-08T10:00:00Z',updated_at:'2026-10-08T10:05:00Z'},...['Vendor onboarding','Annual services agreement','Delivery schedule','Security policy'].map((title,i)=>({id:`audit-${i}`,title:`Preview · ${title}`,status:['completed','processing','queued','failed'][i],created_at:'2026-10-08T09:00:00Z',updated_at:'2026-10-08T09:05:00Z'}))];
let flags=[{id:'flag-1',audit_id:id,document_id:'document-1',claim_id:null,type:'COMMERCIAL_VALUE',severity:'CRITICAL',materiality:'MATERIAL',reason:'The draft states ₹1.25 crore; the approved schedule lists ₹83.4 lakh. The ₹41.6 lakh difference requires a reviewer decision.',suggested_fix:'Reconcile the contract value against the latest approved commercial schedule.',status:'pending',reviewer_note:null,impact_score:28,location_json:'{"page":3,"section":"4.2"}'},{id:'flag-2',audit_id:id,document_id:'document-2',claim_id:null,type:'DELIVERY_DATE',severity:'HIGH',materiality:'HIGH',reason:'The delivery date differs between the draft and the signed schedule.',suggested_fix:'Confirm the signed delivery milestone with the project owner.',status:'pending',reviewer_note:null,impact_score:14,location_json:'{"page":7,"section":"2.1"}'}];
const documents=[{id:'document-1',filename:'Procurement_Agreement_Draft.pdf',kind:'primary',version_no:1,text_hash:'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',is_current:true},{id:'document-2',filename:'Approved_Commercial_Schedule.xlsx',kind:'primary',version_no:2,text_hash:'b5af45644298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b8',is_current:true}];
let score=58,role='reviewer',mode='normal',submitted=false,decisions=0,summaryCalls=0;
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chromium',args:['--disable-gpu','--disable-renderer-backgrounding','--disable-background-timer-throttling']});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{sessionStorage.setItem('tathya-splash-seen','1');localStorage.setItem('access_token','design-preview');localStorage.setItem('vite-ui-theme','light')});
 await page.route('**/api/v1/users/me',r=>r.fulfill({json:{id:'preview',email:'preview@example.in',full_name:'Preview Reviewer',is_active:true,is_superuser:false,role}}));
 await page.route('**/api/v1/audits**',async r=>{
  const path=new URL(r.request().url()).pathname;
  if(mode==='unavailable'){await r.fulfill({status:404,json:{detail:'Not Found'}});return}
  if(path.endsWith('/decision')){const body=r.request().postDataJSON();if(!body.note)throw Error('Missing reviewer note');flags=flags.map(f=>path.includes(f.id)?{...f,status:body.action==='dismiss'?'dismissed':'accepted',reviewer_note:body.note}:f);decisions++;await r.fulfill({json:{id:'decision-1'}});return}
  if(path.endsWith('/rescore')){score=86;await r.fulfill({json:{trust_score:score}});return}
  if(path.endsWith('/flags')){await r.fulfill({json:{data:mode==='processing'&&summaryCalls<2?[]:flags,count:flags.length}});return}
  if(path.endsWith('/documents')){await r.fulfill({json:{data:documents,count:2}});return}
  if(path.endsWith('/audits')&&r.request().method()==='POST'){const body=r.request().postDataBuffer().toString();if(!body.includes('filename="agreement.txt"')||!body.includes('Draft agreement'))throw Error('Multipart file data missing');submitted=true;await r.fulfill({status:201,json:records[0]});return}
  if(path.endsWith('/audits')&&mode==='malformed'){await r.fulfill({json:{data:[{id:'broken'}],count:1}});return} if(path.endsWith('/audits')){await r.fulfill({json:{data:mode==='empty'?[]:records,count:mode==='empty'?0:records.length}});return}
  if(mode==='processing')summaryCalls++; await r.fulfill({json:{audit:{...records[0],status:mode==='processing'&&summaryCalls<2?'processing':'completed'},document_count:2,flag_count:2,open_flag_count:flags.filter(f=>f.status==='pending').length,claim_count:24,passport:{trust_score:score,status:'VERIFIED',verify_token:'previewtoken'}}});
 });

 let items=[],calls=[];
 console.log('Browser ready');await page.route('**/api/v1/items/**',async r=>{const method=r.request().method();calls.push(method);if(method==='GET'){await r.fulfill({json:{data:items,count:items.length}});return}if(method==='POST'){const data=r.request().postDataJSON();items=[{id:'preview-item',owner_id:'preview',...data}];await r.fulfill({status:201,json:items[0]});return}if(method==='PUT'){items=[{...items[0],...r.request().postDataJSON()}];await r.fulfill({json:items[0]});return}if(method==='DELETE'){items=[];await r.fulfill({json:{message:'Item deleted successfully'}});return}throw Error('Unexpected method '+method)});
 page.setDefaultTimeout(60000);await page.goto('http://127.0.0.1:4173/items');console.log('Items page loaded');await expect(page.getByRole('heading',{name:'Items',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:"You don't have any items yet"})).toBeVisible();console.log('Empty state verified');await page.getByRole('button',{name:'Add Item',exact:true}).click({force:true});await page.getByLabel('Title',{exact:false}).fill('Preview item');await page.getByLabel('Description',{exact:true}).fill('Sample record for behaviour verification');await page.getByRole('button',{name:'Save',exact:true}).click({force:true});await expect(page.getByText('Preview item',{exact:true})).toBeVisible();console.log('Create verified');await page.getByRole('button',{name:'Manage Preview item'}).click({force:true});await page.getByRole('menuitem',{name:'Edit Item'}).click({force:true});await page.getByLabel('Title',{exact:false}).fill('Preview edited');await page.getByRole('button',{name:'Save',exact:true}).click({force:true});await expect(page.getByText('Preview edited',{exact:true})).toBeVisible();console.log('Edit verified');await page.screenshot({path:'artifacts/ui-review/items-preserved.png',fullPage:true});await page.getByRole('button',{name:'Manage Preview edited'}).click({force:true});await page.getByRole('menuitem',{name:'Delete Item'}).click({force:true});await page.getByRole('button',{name:'Delete',exact:true}).click({force:true});await expect(page.getByRole('heading',{name:"You don't have any items yet"})).toBeVisible();if(errors.length || !['POST','PUT','DELETE'].every(m=>calls.includes(m)))throw Error(JSON.stringify({errors,calls}));await browser.close();console.log(JSON.stringify({passed:true,checks:['existing item creation','existing item edit','existing item deletion','empty state'],errors}));
})().catch(e=>{console.error(e);process.exit(1)});
