"""tathya_initial_schema

Revision ID: 14028be804b3
Revises: fe56fa70289e
Create Date: 2026-10-09 00:59:33.251852

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '14028be804b3'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rules_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audits',
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('failed_stage', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('source_set_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('previous_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_audit_id'), 'audit_log', ['audit_id'], unique=False)
    op.create_table('documents',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('raw_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('offset_map_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('blocks_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('mtime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id', 'version_no', name='uq_documents_audit_version')
    )
    op.create_index('ix_documents_audit_current', 'documents', ['audit_id', 'is_current'], unique=False)
    op.create_index(op.f('ix_documents_audit_id'), 'documents', ['audit_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('passports',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('verify_token', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('document_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('chain_head', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('signature', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passports_audit_id'), 'passports', ['audit_id'], unique=True)
    op.create_index(op.f('ix_passports_verify_token'), 'passports', ['verify_token'], unique=True)
    op.create_table('claims',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('sentence_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_claims_audit_document', 'claims', ['audit_id', 'document_id'], unique=False)
    op.create_index(op.f('ix_claims_audit_id'), 'claims', ['audit_id'], unique=False)
    op.create_index(op.f('ix_claims_document_id'), 'claims', ['document_id'], unique=False)
    op.create_table('facts',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('predicate', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('object_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facts_document_id'), 'facts', ['document_id'], unique=False)
    op.create_table('evidence',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=False),
    sa.Column('quote', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('support_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_claim_id'), 'evidence', ['claim_id'], unique=False)
    op.create_index(op.f('ix_evidence_source_document_id'), 'evidence', ['source_document_id'], unique=False)
    op.create_table('flags',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('materiality', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('suggested_fix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('reviewer_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=False),
    sa.Column('sentence_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('location_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_flags_audit_document', 'flags', ['audit_id', 'document_id'], unique=False)
    op.create_index(op.f('ix_flags_audit_id'), 'flags', ['audit_id'], unique=False)
    op.create_index(op.f('ix_flags_document_id'), 'flags', ['document_id'], unique=False)
    op.create_table('proofs',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=True),
    sa.Column('solver', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proofs_audit_id'), 'proofs', ['audit_id'], unique=False)
    op.create_table('challenges',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('flag_id', sa.Uuid(), nullable=True),
    sa.Column('raised_by', sa.Uuid(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('resolution', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['flag_id'], ['flags.id'], ),
    sa.ForeignKeyConstraint(['raised_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_audit_id'), 'challenges', ['audit_id'], unique=False)
    op.create_table('decisions',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('flag_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['flag_id'], ['flags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_audit_id'), 'decisions', ['audit_id'], unique=False)
    op.create_index(op.f('ix_decisions_flag_id'), 'decisions', ['flag_id'], unique=False)
    op.drop_table('item')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey'))
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('item',
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('item_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('item_pkey'))
    )
    op.drop_index(op.f('ix_decisions_flag_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_audit_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_challenges_audit_id'), table_name='challenges')
    op.drop_table('challenges')
    op.drop_index(op.f('ix_proofs_audit_id'), table_name='proofs')
    op.drop_table('proofs')
    op.drop_index(op.f('ix_flags_document_id'), table_name='flags')
    op.drop_index(op.f('ix_flags_audit_id'), table_name='flags')
    op.drop_index('ix_flags_audit_document', table_name='flags')
    op.drop_table('flags')
    op.drop_index(op.f('ix_evidence_source_document_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_claim_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_facts_document_id'), table_name='facts')
    op.drop_table('facts')
    op.drop_index(op.f('ix_claims_document_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_audit_id'), table_name='claims')
    op.drop_index('ix_claims_audit_document', table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_passports_verify_token'), table_name='passports')
    op.drop_index(op.f('ix_passports_audit_id'), table_name='passports')
    op.drop_table('passports')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_documents_audit_id'), table_name='documents')
    op.drop_index('ix_documents_audit_current', table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_log_audit_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('items')
    op.drop_table('audits')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('policies')
    # ### end Alembic commands ###
