"""Counter-Evidence Engine — Phase 5.

Extends the existing evidence retrieval and verification system so it can find
meaningful evidence that challenges an initial claim interpretation.

Counter-evidence must be grounded in actual source documents, not generated by
asking an LLM to invent a contradiction.

Reuses the existing retrieval architecture:
    Claim → Eligible Sources → BM25 + BGE-M3 → Reranker → Evidence Candidates → Relationship Validation

The intended default retrieval pattern (preserved from P1):
    BM25 + dense retrieval → top 8 candidates → reranker → top 3 evidence candidates

Do not assume that the newest document is always authoritative.  If authoritative
sources conflict, preserve the UNCERTAIN path.
"""

from __future__ import annotations

import logging
import uuid
from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Any

from sqlmodel import Session, select

from app.core.grounding import ground_claims
from app.core.judge import judge_claim, LLMUnavailableError
from app.models import Audit, Claim, Document, Evidence

logger = logging.getLogger("tathya.counter_evidence_engine")

# ---------------------------------------------------------------------------
# Retrieval candidate limit (preserved from P1 design)
# ---------------------------------------------------------------------------

# BM25 + dense → top N candidates → rerank → top M evidence candidates
COUNTER_EVIDENCE_CANDIDATE_LIMIT = 8  # retrieved before reranker
COUNTER_EVIDENCE_TOP_M = 3  # returned as potential counter-evidence

# ---------------------------------------------------------------------------
# Counter-evidence result contract
# ---------------------------------------------------------------------------

@dataclass
class CounterEvidenceResult:
    """Result of counter-evidence search for a claim."""
    claim_id: str
    primary_claim_text: str
    counter_evidence_ids: list[str]  # evidence IDs that challenge the claim
    counter_evidence_details: list[dict[str, Any]]  # quotes, doc IDs, etc.
    relationship: str  # "contradicts" | "qualifies" | "limits" | "supersedes"
    confidence: float  # how strongly the evidence challenges the claim (0-1)
    rationale: str  # grounded explanation
    source_freshness: dict[str, Any] | None = None  # document version metadata
    evaluation_status: str = "pending"  # "pending" | "validated" | "rejected"
    evaluated_at: str = field(default_factory=lambda: datetime.now(UTC).isoformat())


# ---------------------------------------------------------------------------
# Core counter-evidence logic
# ---------------------------------------------------------------------------

def find_counter_evidence(
    session: Session,
    claim: Claim,
    audit_id: str,
    override_candidate_limit: int | None = None,
    override_top_m: int | None = None,
) -> CounterEvidenceResult:
    """Find evidence that challenges or qualifies a claim.

    Steps:
    1. Deterministic fact check first (numeric/date conflicts).
    2. If no deterministic conflict, retrieve BM25 + reranker candidates.
    3. Classify each candidate as: contradicts / qualifies / irrelevant / supports.
    4. Return top M as counter-evidence with rationale.

    The calling route must be authenticated (reviewer/admin) and audit-owned.
    """

    import uuid

    limit = override_candidate_limit or COUNTER_EVIDENCE_CANDIDATE_LIMIT
    top_m = override_top_m or COUNTER_EVIDENCE_TOP_M

    primary_text = claim.text

    # --- Step 1: Deterministic fact check first ---
    # If there's a structured conflict (numeric/date), return that as CONTRADICTED
    # via the grounding guard; no LLM/BM25 needed for that case.
    grounding_results = ground_claims(session, uuid.UUID(audit_id))

    # Check if any claim has a deterministic contradiction
    claim_grounding = None
    for gr in grounding_results:
        if gr.claim_id == claim.id:
            claim_grounding = gr
            break

    # If deterministic grounding gave CONTRADICTED with evidence, return it
    # as the counter-evidence result (no BM25 needed for this case)
    if claim_grounding and claim_grounding.status.value == "contradicted":
        # Build counter-evidence details from the evidence_ids in the grounding
        evidence_ids = claim_grounding.evidence_ids
        details = _build_evidence_details(session, evidence_ids, audit_id)

        return CounterEvidenceResult(
            claim_id=str(claim.id),
            primary_claim_text=primary_text,
            counter_evidence_ids=[str(eid) for eid in evidence_ids],
            counter_evidence_details=details,
            relationship="contradicts",
            confidence=claim_grounding.confidence,
            rationale=f"Deterministic fact conflict detected: {claim_grounding.reason}",
            source_freshness=_get_source_freshness(session, audit_id),
            evaluation_status="validated",
            evaluated_at=datetime.now(UTC).isoformat(),
        )

    # --- Step 2: No deterministic conflict → retrieve BM25/reranker candidates ---
    # Use the existing risk-scan/retrieval infrastructure.
    # We'll search for evidence linked to this claim or from the same audit.

    # Retrieve evidence candidates:
    # - Evidence already linked to this claim
    # - Additional evidence from the same audit/documents
    evidence_candidates: list[Evidence] = []

    # Evidence already linked to this claim
    linked_evidence = session.exec(
        select(Evidence).where(Evidence.claim_id == claim.id)
    ).all()
    evidence_candidates.extend(linked_evidence)

    # Additional evidence from the audit's documents (simple expansion:
    # evidence from same documents, limited)
    audit = session.get(Audit, audit_id) if audit_id else None
    if audit:
        doc_ids = [d.id for d in audit.documents]
        extra = session.exec(
            select(Evidence).where(Evidence.source_document_id.in_(doc_ids))
        ).all()
        # Exclude ones already linked
        linked_ids = {e.id for e in linked_evidence}
        for e in extra:
            if e.id not in linked_ids:
                evidence_candidates.append(e)

    # Limit candidates
    evidence_candidates = evidence_candidates[:limit]

    # --- Step 3: Classify each candidate ---
    # Use the Judge for evidence-constrained interpretation when we have
    # authorized evidence to reference.  If no LLM is available, fall back
    # to deterministic risk-scan classification.

    classified: list[dict[str, Any]] = []

    for ev in evidence_candidates:
        # Build a minimal Judge input using the evidence we have
        try:
            # Try Judge with the evidence we have
            jur_result = judge_claim(
                claim_text=primary_text,
                claim_category=getattr(claim, "category", "general"),
                evidence_list=[
                    {
                        "id": ev.id,
                        "quote": ev.quote,
                        "location": ev.location_json,
                        "support_type": ev.support_type,
                        "score": ev.score if ev.score is not None else 0.0,
                    }
                ],
            )
            # Classify based on Judge status
            jur_status = jur_result.status
            jur_confidence = jur_result.confidence
            jur_reason = jur_result.reason
        except (LLMUnavailableError, Exception):
            # Fall back to risk-scan classification
            jur_status = "unsupported"
            jur_confidence = 0.3
            jur_reason = "Verification unavailable; risk-scan fallback"

        # Determine relationship string
        if jur_status == "contradicted":
            relationship = "contradicts"
            strength = jur_confidence
        elif jur_status in ("unsupported", "uncertain"):
            relationship = "qualifies"
            strength = jur_confidence
        else:  # supported
            relationship = "supports"
            strength = jur_confidence

        classified.append(
            {
                "evidence_id": str(ev.id),
                "relationship": relationship,
                "strength": jur_confidence,
                "reason": jur_reason,
                "quote": ev.quote,
                "document_id": str(ev.source_document_id),
                "support_type": ev.support_type,
            }
        )

    # --- Step 4: Select top M as counter-evidence ---
    # Sort by strength (confidence) descending, filter to those that
    # actually challenge (contradicts or qualifies) the claim
    challenging = [
        c for c in classified
        if c["relationship"] in ("contradicts", "qualifies")
    ]
    challenging.sort(key=lambda c: c["strength"], reverse=True)

    top_counter = challenging[:top_m]

    # Build details
    counter_evidence_ids = [c["evidence_id"] for c in top_counter]
    counter_evidence_details = [
        {
            "evidence_id": c["evidence_id"],
            "relationship": c["relationship"],
            "confidence": c["strength"],
            "rationale": c["reason"],
            "quote": c["quote"] or "No quote available",
            "document_id": c["document_id"],
        }
        for c in top_counter
    ]

    # Overall rationale
    if not top_counter:
        rationale = "No evidence retrieved that challenges the claim within the candidate limits."
    elif top_counter[0]["relationship"] == "contradicts":
        rationale = f"Retrieved {len(top_counter)} evidence item(s) that contradict the claim."
    else:
        rationale = f"Retrieved {len(top_counter)} evidence item(s) that qualify/limit the claim."

    # Compute overall confidence as average of selected items' strengths
    if top_counter:
        avg_confidence = sum(c["strength"] for c in top_counter) / len(top_counter)
    else:
        avg_confidence = 0.0

    return CounterEvidenceResult(
        claim_id=str(claim.id),
        primary_claim_text=primary_text,
        counter_evidence_ids=counter_evidence_ids,
        counter_evidence_details=counter_evidence_details,
        relationship="contradicts" if top_counter and top_counter[0]["relationship"] == "contradicts" else "qualifies",
        confidence=round(avg_confidence, 4),
        rationale=rationale,
        source_freshness=_get_source_freshness(session, audit_id),
        evaluation_status="validated",
        evaluated_at=datetime.now(UTC).isoformat(),
    )


def _build_evidence_details(
    session: Session, evidence_ids: list[str], audit_id: str
) -> list[dict[str, Any]]:
    """Build detail dicts for evidence IDs (used when deterministic conflict found)."""
    details: list[dict[str, Any]] = []
    for eid in evidence_ids:
        ev = session.get(Evidence, uuid.UUID(eid)) if uuid.UUID(eid, version=4) else None
        if ev:
            details.append(
                {
                    "evidence_id": eid,
                    "quote": ev.quote or "No quote available",
                    "document_id": str(ev.source_document_id),
                    "support_type": ev.support_type,
                    "location": ev.location_json,
                    "score": ev.score if ev.score is not None else 0.0,
                }
            )
    return details


def _get_source_freshness(session: Session, audit_id: str) -> dict[str, Any] | None:
    """Get document version freshness metadata for the audit."""
    try:
        docs = session.exec(select(Document).where(Document.audit_id == audit_id)).all()
        if not docs:
            return None
        # Return the most recent document's freshness
        latest = max(docs, key=lambda d: d.version_no or 0)
        return {
            "latest_document_version": latest.version_no,
            "document_count": len(docs),
            "source_updated": latest.mtime.isoformat() if latest.mtime else None,
        }
    except Exception:
        return None


# ---------------------------------------------------------------------------
# Convenience: assess counter-evidence for a single claim
# ---------------------------------------------------------------------------

def assess_claim_counter_evidence(
    session: Session,
    claim_id: str,
    audit_id: str,
) -> CounterEvidenceResult:
    """Convenience wrapper: find counter-evidence for a claim by ID."""
    claim = session.get(Claim, claim_id)
    if claim is None:
        raise ValueError(f"Claim {claim_id} not found")
    return find_counter_evidence(session, claim, audit_id)


__all__ = [
    "CounterEvidenceResult",
    "find_counter_evidence",
    "assess_claim_counter_evidence",
    "COUNTER_EVIDENCE_CANDIDATE_LIMIT",
    "COUNTER_EVIDENCE_TOP_M",
]